[tool.poetry]
name = "copy-twitterbio"
version = "0.1.0"
description = ""
authors = ["Shin-jay7 <shin@jay7.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
